'''
Type stubs for geometric utilities.
'''

from typing import Tuple, List

class Point:
    x: float
    y: float

    def __init__(self, x: float, y: float) -> None: ...
    def distance_to(self, other: 'Point') -> float: ...
    def __repr__(self) -> str: ...

class Line:
    start: Point
    end: Point

    def __init__(self, start: Point, end: Point) -> None: ...
    def length(self) -> float: ...
    def midpoint(self) -> Point: ...
    def __repr__(self) -> str: ...

def distance_between_points(p1: Point, p2: Point) -> float: ...
def get_bounding_box(points: List[Point]) -> Tuple[Point, Point]: ...
